### PR TITLE
feat(examples): Implement Domain package (Gno Name Service)

### PR DESCRIPTION
**Pull request by linhpn99**
<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

### CODE REVIEW

**Comment by thinhnx-var** [comment]
@linhpn99 changed base branch to feature branch, then we can make the pull request to master repo without refactor our master br. 🚀

**Comment by linhpn99** [comment]
> @linhpn99 changed base branch to feature branch, then we can make the pull request to master repo without refactor our master br. 🚀 
> 
> 

This PR is just an announcement about the feature being developed/nearing completion

**Comment by linhpn99** [comment]
We will create a PR to the master branch of Gno along with your realms @thinhnx-var

**Comment by thinhnx-var** [comment]
@linhpn99  yeah, and this way is easier for squash and merge the commit.  `gno-core-team` <- `Var-gno/dev-feature` <- `this define-gns` <- commit to this. Then the history should look so good and clean.

**Pull request merged**
